{% set name = "polar-codes" %}
# Set package version from cleaned up git tags if possible,
# otherwise fall back to date-based version.
{% set tag_version = environ.get("GIT_DESCRIBE_TAG", "")|string|replace("-","_")|replace("v","")|replace("git","") %}
{% set post_commit = environ.get("GIT_DESCRIBE_NUMBER", 0)|string %}
{% set hash = environ.get("GIT_DESCRIBE_HASH", "local")|string %}
{% set fallback_version = "0.0.0.{0}.dev+g{1}".format(datetime.datetime.now().strftime("%Y%m%d"), environ.get("GIT_FULL_HASH", "local")[:9]) %}
{% set version = (tag_version if post_commit == "0" else "{0}.post{1}+{2}".format(tag_version, post_commit, hash)) if tag_version else fallback_version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # use local path or git repository depending on if the build is local or done on CI
  path: "../.."  # [not os.environ.get("CI")]
  git_url: {{ environ.get('FEEDSTOCK_ROOT', "../..") }}  # [os.environ.get("CI")]

build:
  skip: True  # [not linux64]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake >=3.16
    - ninja
    - pkg-config  # [not win]

  host:
    - python
    - numpy >=1.22
    - scipy >=1.10
    - fmt
    - pybind11
    - openssl
    - cppunit
    - tclap

  run:
    - python
    - scipy >=1.10

test:
  imports:
    - pypolar

about:
  home: https://github.com/ant-uni-bremen/polar-codes
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: "A highly-optimized library and simulation tool for polar-codes."
  doc_url: https://github.com/ant-uni-bremen/polar-codes
  dev_url: https://github.com/ant-uni-bremen/polar-codes

extra:
  recipe-maintainers:
    - jdemel
