name: Check C++ code formatting with clang-format

on:
  push:
    paths-ignore:
      - 'doc/'
  pull_request:
    paths-ignore:
      - 'doc/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - uses: gnuradio/clang-format-lint-action@v0.5-4
      with:
        source: '.'
        extensions: 'c,cc,cpp,cxx,h,hh'
