name: Run CI tests

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: dependencies
      run: sudo apt install doxygen python3-pybind11 python3-numpy python3-scipy libcppunit-dev libtclap-dev libssl-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: install
      run: cd build && sudo make install
    - name: test
      run: cd build && ctest -V
